In [1]:
lict = [1,2,3,4,5,6]

In [2]:
lict [0]

1

In [3]:
lict[0:4]

[1, 2, 3, 4]

In [4]:
lict[0:4:2]

[1, 3]

In [5]:
for x in lict:
    print(x)

1
2
3
4
5
6


In [6]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [8]:
for x in range(1,20,2):
    print(x)

1
3
5
7
9
11
13
15
17
19


In [9]:
len(lict)

6

In [10]:
lict = ['string',2,2.4]

In [11]:
lict

['string', 2, 2.4]

In [12]:
import numpy as np

In [13]:
l = range(100000)

In [14]:
a = np.arange(100000)

In [16]:
%time for x in range(1,20): r=[i*2 for i in l]

CPU times: user 212 ms, sys: 22.9 ms, total: 235 ms
Wall time: 253 ms


In [17]:
%time for x in range(1,20): r= a*2

CPU times: user 8.9 ms, sys: 0 ns, total: 8.9 ms
Wall time: 40.8 ms


In [18]:
type(a)

numpy.ndarray

In [19]:
b = np.array(4)

In [20]:
print(b)

4


In [21]:
b.ndim

0

In [22]:
c = np.array([1,2,3,4])

In [23]:
c.ndim

1

In [24]:
c = np.array([1,2,3,4],ndmin=4)

In [25]:
c.ndim

4

In [26]:
c

array([[[[1, 2, 3, 4]]]])

In [32]:
d = np.array([1,23,43],dtype='float')

In [33]:
type(d)

numpy.ndarray

In [34]:
d

array([ 1., 23., 43.])

In [37]:
e = np.zeros((3,4))

In [38]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
f = np.ones((3,3))

In [40]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
g = np.identity(4)

In [43]:
g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
g.shape

(4, 4)

In [45]:
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [46]:
b

array(4)

In [47]:
arra = np.array([1,3,4,3,2,4])

In [48]:
arra[0]

1

In [49]:
arra[0:4]

array([1, 3, 4, 3])