In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

In [8]:
a = np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(1000*(toc-tic))
print(c)

0.5412101745605469
24987.60642611544


In [7]:
d = 0
tic = time.time()
for i in range(100000):
    d += a[i]*b[i]
toc = time.time()
print(1000*(toc-tic))
print(d)

118.97492408752441
25057.73252708437


In [2]:
#broadcasting

In [3]:
import numpy as np

In [9]:
A = np.random.randn(3,4)

In [10]:
A

array([[ 1.02907413, -1.44273565, -0.38707343,  0.06087234],
       [-0.2082965 ,  0.78778929,  0.38564361, -1.31802905],
       [ 1.82124882, -1.5658939 , -0.26077695,  0.82765537]])

In [11]:
cal = A.sum(axis=0)

In [12]:
cal

array([ 2.64202646, -2.22084026, -0.26220677, -0.42950134])

In [15]:
cal.reshape(1,4)

array([[ 2.64202646, -2.22084026, -0.26220677, -0.42950134]])

In [16]:
percentage = 100*(A/cal.reshape(1,4))

In [17]:
percentage

array([[  38.9501828 ,   64.96350401,  147.62144949,  -14.17279449],
       [  -7.88396719,  -35.47257793, -147.0761482 ,  306.87425797],
       [  68.93378439,   70.50907392,   99.4546987 , -192.70146348]])