# File Input and Output with Arrays

In [5]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
np.save('myarr',arr)

In [4]:
np.load('myarr.npy')

array([1, 2, 3, 4, 5])

In [6]:
np.save('arrp.npy',arr)

In [7]:
np.load('arrp.npy')

array([1, 2, 3, 4, 5])

In [8]:
arrayload = np.load('arrp.npy')

In [9]:
arrayload

array([1, 2, 3, 4, 5])

In [12]:
np.save('arrp.npy',arr)

In [13]:
arr2 = np.array([-1,-2,-3,-4])

In [14]:
np.savez('array-collection.npz', a=arr,b=arr)

In [15]:
archive = np.load('array-collection.npz')

In [16]:
archive['a']

array([1, 2, 3, 4, 5])

In [17]:
archive['b']

array([1, 2, 3, 4, 5])

# astype

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr.dtype

dtype('int32')

In [20]:
arr = arr.astype('float')

In [21]:
arr.dtype

dtype('float64')

In [22]:
arr = arr.astype('int')

In [23]:
arr.dtype

dtype('int32')

# Transpose

In [24]:
arr3 = np.arange(15).reshape(3,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr3.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
arr4 = np.array([[[1,2,3,4],[1,2,3,4]],[[-1,-2,-3,-4],[-1,-2,-3,-4]]])

In [32]:
arr4.ndim

3

In [33]:
arr4

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4]],

       [[-1, -2, -3, -4],
        [-1, -2, -3, -4]]])

In [34]:
arr4.transpose()

array([[[ 1, -1],
        [ 1, -1]],

       [[ 2, -2],
        [ 2, -2]],

       [[ 3, -3],
        [ 3, -3]],

       [[ 4, -4],
        [ 4, -4]]])

# Fancy Indexing

In [35]:
arr5 = np.arange(16).reshape(4,4)

In [36]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
arr5[[0,1,2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
arr5[[0,1],[0,1]]

array([0, 5])

In [41]:
arr5[[0,2]][:,[2,0,1]]

array([[ 2,  0,  1],
       [10,  8,  9]])

# Boolean Indexing

In [42]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
arr5[arr5>5]=2

In [45]:
arr5

array([[0, 1, 2, 3],
       [4, 5, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])