In [1]:
%time lest = list(range(1000000))

CPU times: user 22.6 ms, sys: 31.8 ms, total: 54.4 ms
Wall time: 70.8 ms


In [2]:
import numpy as np

In [3]:
%time a1 = np.arange(1,1000000)

CPU times: user 0 ns, sys: 5.97 ms, total: 5.97 ms
Wall time: 6.76 ms


In [4]:
%time [x+5 for x in lest][:10]

CPU times: user 105 ms, sys: 23.5 ms, total: 129 ms
Wall time: 149 ms


[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [5]:
a1.ndim

1

In [6]:
a1.shape

(999999,)

In [7]:
a1.dtype

dtype('int64')

In [8]:
l1 = np.random.randn(2,2)
print(l1)
print(l1.ndim)
print(l1.dtype)
print(l1.shape)

[[-0.01125662  1.96181573]
 [-0.84301029 -0.6503362 ]]
2
float64
(2, 2)


In [9]:
l2 = np.random.randn(2,3,4)
print(l2)
print(l2.ndim)
print(l2.dtype)
print(l2.shape)

[[[-0.68012207  0.403845    2.38150882 -0.22625662]
  [ 0.3981198   1.45238481  0.51057926 -0.60902198]
  [ 0.60141339 -0.8675164   0.0391426  -0.9979671 ]]

 [[ 0.68581194 -0.91500472  0.17649064 -0.25338764]
  [-1.02207158 -0.74102796 -0.36198494  1.19970698]
  [-0.73698948 -0.61458549 -0.67086399 -1.32157956]]]
3
float64
(2, 3, 4)


In [10]:
l3 = np.arange(27).reshape(3,3,3)

In [11]:
l3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
l3[1,2,2]

17

In [13]:
l4 = np.arange(1,26).reshape(5,5)
print(l4)
print(l4.ndim)
print(l4.dtype)
print(l4.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2
int64
(5, 5)


In [14]:
print(l4.itemsize)

8


In [15]:
l4 = np.random.randn(3,4)
print(l4)
print(l4.ndim)
print(l4.dtype)
print(l4.shape)

[[ 0.35630351  1.4148665   0.33665214 -1.10543685]
 [ 0.03857708  0.13414066  1.10386882  2.42642012]
 [ 0.19420199  0.04079405 -0.36848549 -1.59559146]]
2
float64
(3, 4)


In [17]:
l4 % 2 == 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
l4[l4 % 2 == 0]

array([], dtype=float64)

In [23]:
l4 > 0.22

array([[ True,  True,  True, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [24]:
l4[l4 > 0.22]

array([0.35630351, 1.4148665 , 0.33665214, 1.10386882, 2.42642012])

In [25]:
l4 ** 2

array([[1.26952193e-01, 2.00184722e+00, 1.13334665e-01, 1.22199062e+00],
       [1.48819084e-03, 1.79937154e-02, 1.21852638e+00, 5.88751462e+00],
       [3.77144136e-02, 1.66415475e-03, 1.35781558e-01, 2.54591212e+00]])

In [26]:
l4

array([[ 0.35630351,  1.4148665 ,  0.33665214, -1.10543685],
       [ 0.03857708,  0.13414066,  1.10386882,  2.42642012],
       [ 0.19420199,  0.04079405, -0.36848549, -1.59559146]])

In [27]:
l1 = [1,2,4,3,6,5]
a = np.array(l1)


In [28]:
b = np.array(a)

In [29]:
a is b

False

In [30]:
type(a)

numpy.ndarray

In [31]:
type(b)

numpy.ndarray

In [32]:
l1 = [1,2,4,3,6,5]
a = np.asarray(l1)
b = np.asarray(a)
a is b

True

In [33]:
l1 is a

False

In [35]:
c = np.asarray(b, dtype=np.float64)

In [36]:
b is c

False