In [1]:
import numpy as np

In [3]:
a = np.array(22)
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

22
<class 'numpy.ndarray'>
int32
0


In [6]:
b = np.array([[1,2,3],[1,2,3]])
print(b)
print(b.ndim)
print(b.dtype)
print(type(b))

[[1 2 3]
 [1 2 3]]
2
int32
<class 'numpy.ndarray'>


In [8]:
c = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(c)
print(c.ndim)
print(c.dtype)
print(type(c))

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
3
int32
<class 'numpy.ndarray'>


In [9]:
c.shape

(2, 2, 4)

In [10]:
b.shape

(2, 3)

In [11]:
a.shape

()

In [13]:
t3d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
t3d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [15]:
arr = np.array([1,2,3,4], ndmin=3)

In [16]:
arr.ndim

3

In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
arr2 = np.arange(14)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [22]:
arr3 = np.arange(12).reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr3 = np.arange(24).reshape(2,3,4)
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr5 = np.zeros((4,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr6 = np.arange((12)).reshape(3,4)

In [29]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr7 = np.ones_like(arr6)

In [31]:
arr7

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
arr8 = np.zeros_like(arr6)
arr8

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr6.max()

11

In [36]:
arr6.min()

0

In [37]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
arr6.mean()

5.5

In [40]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [42]:
a1 = np.array([1,2,3,4,5,6,7])
a1

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
a1[3:5]

array([4, 5])

In [45]:
a1

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
a1[0]

1

In [47]:
a1[[1,2,3,4]]

array([2, 3, 4, 5])

In [48]:
a1[[0,5,6]]

array([1, 6, 7])

In [49]:
a1[0]

1

In [50]:
a2 = np.arange(12).reshape(4,3)

In [51]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
a2[[1,2,3],[0,1,2]]

array([ 3,  7, 11])