In [1]:
import numpy as np

In [4]:
# array element can accessed by referring to its index number - indexes in numPy arrays start with 0


arr = np.array([1,2,3,4,5,6,7])
print(arr[2])

3


In [5]:
# accessing 5th element 


print(arr[4])

5


In [6]:
# addition of different elements from array


print(arr[2]+ arr[1])

5


# 2-D ARRAYS 

In [7]:
arr2d = np.array([[4,3,2,1],[1,2,3,4]])
print(arr2d)

[[4 3 2 1]
 [1 2 3 4]]


In [11]:
# comma separated integers used to represent the dimension and the index of the element
# to access the 3rd element on 1st dim


print(arr2d[0,2])

2


In [12]:
# to access the 1st element on 2nd dim


print(arr2d[1,0])

1


# 3-D ARRAYS

In [13]:
arr3d = np.array([[[1,2,3,4],[5,6,7,8]],[[8,7,6,5],[4,3,2,1]]])
print(arr3d)

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]


In [14]:
# comma separated integers used to represent the dimension and the index of the element
# to access the third element of the second array of the first array


print(arr3d[0,1,2])

7


In [15]:
# to access the 2nd element of the 2nd array of the 2nd array


print(arr3d[1,1,1])

3


# Negative Indexing

In [16]:
print(arr2d)

[[4 3 2 1]
 [1 2 3 4]]


In [17]:
# use negative indexing to access an array from the end


print(arr2d[1, -1])

4


In [18]:
print(arr2d[1,-4])

1


In [19]:
print(arr2d[0,-2])

2
