In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4])

In [3]:
a1

array([1, 2, 3, 4])

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2 = a1.astype(np.float64)

In [6]:
a2

array([1., 2., 3., 4.])

In [8]:
a2.dtype

dtype('float64')

In [9]:
a1

array([1, 2, 3, 4])

In [11]:
a3 = a1[2:5]

In [12]:
a3

array([3, 4])

In [14]:
a1[3] =5

In [15]:
a3

array([3, 5])

In [16]:
a1

array([1, 2, 3, 5])

In [17]:
a5 = np.arange(16).reshape(4,4)

In [18]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
a5[0,1]

1

In [21]:
a5[0][1]

1

In [23]:
a6 = np.arange(16).reshape(2,2,4)

In [24]:
a6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
a6[0,1]

array([4, 5, 6, 7])

In [27]:
a6[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
a7 = np.arange(9).reshape(3,3)

In [32]:
a7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
a7[:2,:2]

array([[0, 1],
       [3, 4]])

In [35]:
a7[:2,2]

array([2, 5])

In [36]:
a7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
an =np.array(['tariq','arslan','zeeshan','usman','arslan'])

In [47]:
ad = np.arange(20).reshape(5,4)

In [48]:
ad

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [49]:
ad[an == "arslan"]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [50]:
ad[~(an=='arslan')]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
ad[an!="arslan"]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
mask = (an == "arslan") | (an=="zeeshan")

In [54]:
mask

array([False,  True,  True, False,  True])

In [55]:
ad[mask]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [56]:
ad[[2,3]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
ad

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
a1 = np.array([1,2,3])
b2 = np.array([3,2,1])

In [59]:
np.dot(a1,b2)

10

In [60]:
q1 = np.array([2,3,4])

In [61]:
np.dot(a1,q1)

20

In [63]:
np.dot(q1,b2)

16

In [65]:
a1 = np.arange(12).reshape(3,4)

In [66]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a1.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
a1.T()

TypeError: 'numpy.ndarray' object is not callable

In [71]:
a = np.array([1,2,3,4])
b = np.array([3,2,4,5])

In [72]:
np.minimum(a,b)

array([1, 2, 3, 4])

In [74]:
np.modf(a)

(array([0., 0., 0., 0.]), array([1., 2., 3., 4.]))

In [75]:
a

array([1, 2, 3, 4])

In [76]:
b

array([3, 2, 4, 5])

In [77]:
np.modf(b)

(array([0., 0., 0., 0.]), array([3., 2., 4., 5.]))

In [79]:
mod = np.arange(23)

In [81]:
mod = b.astype(np.float64)

In [82]:
mod

array([3., 2., 4., 5.])

In [84]:
np.modf(mod)

(array([0., 0., 0., 0.]), array([3., 2., 4., 5.]))

In [85]:
c = np.array([2.2,3.2,4.2,1.2])

In [86]:
c

array([2.2, 3.2, 4.2, 1.2])

In [87]:
np.modf(c)

(array([0.2, 0.2, 0.2, 0.2]), array([2., 3., 4., 1.]))

In [88]:
a1 = np.array([1,2,3,4])

In [92]:
np.square(a1)

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
np.abs(a1)

array([1, 2, 3, 4])

In [94]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [95]:
np.sign(a1)

array([1, 1, 1, 1])

In [97]:
np.add(a1,b1)

array([2, 4, 6, 8])

In [96]:
b1 = np.array([1,2,3,4])

In [98]:
np.greater(a1,b1)

array([False, False, False, False])

In [99]:
np.greater_equal(a1,b1)

array([ True,  True,  True,  True])

In [100]:
np.meshgrid(a1,b1)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]), array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])]

In [101]:
a1

array([1, 2, 3, 4])

In [102]:
a1.min()

1

In [105]:
a4 = np.array([4,3,2,1])

In [104]:
a1

array([1, 2, 3, 4])

In [106]:
np.sort(a4)

array([1, 2, 3, 4])