In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(arr.dtype)

int64


In [4]:
arr = np.array(['a','b','c'])
print(arr)
print(arr.dtype)

['a' 'b' 'c']
<U1


In [5]:
print(arr.dtype)

<U1


In [6]:
arr = np.array([1,2,4,3,6], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'4' b'3' b'6']
|S1


In [7]:
arr = np.array([1,2,3,5],dtype='i4')

In [8]:
print(arr)

[1 2 3 5]


In [9]:
arr.dtype

dtype('int32')

In [10]:
arr = np.array([1.2,2.4,3.3,4.2])

In [11]:
arr

array([1.2, 2.4, 3.3, 4.2])

In [12]:
ar = arr.astype('i')

In [13]:
ar

array([1, 2, 3, 4], dtype=int32)

In [14]:
ar.dtype

dtype('int32')

In [15]:
arr = np.array([1.2,3.3,45.5,3.2])

In [16]:
arr.astype(int)

array([ 1,  3, 45,  3])

In [17]:
arr = np.array([1,2,0,3])

In [18]:
arr.astype(bool)

array([ True,  True, False,  True])