In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


In [3]:
print(arr[4:])

[5 6 7]


In [4]:
print(arr[0:4])

[1 2 3 4]


In [5]:
print(arr[:4])

[1 2 3 4]


In [6]:
print(arr[-3:-1])

[5 6]


In [7]:
print(arr[-1])

7


In [8]:
print(arr[-2])

6


In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
print(arr)

[1 2 3 4 5 6 7]


In [11]:
print(arr[1:6:2])

[2 4 6]


# Return every other element from the entire array:

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
arr[::2]

array([1, 3, 5, 7])

# 2D

In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [16]:
arr[1,0:2]

array([6, 7])

In [17]:
arr[0,0:2]

array([1, 2])

In [18]:
arr[0:2,2]

array([3, 8])

In [19]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [20]:
array = arr[0:2,1:4]

In [22]:
type(array)

numpy.ndarray

In [23]:
array.dtype

dtype('int64')

In [24]:
array.ndim

2