In [3]:
# import it in your program by using the import keyword


import numpy as np

In [5]:
# creation of NumPy ndarray object by using the array() function


arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [6]:
# type() function tells us the type of the object passed to it


print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
# for creating an ndarray, a list, tuple or any array-like object can be passed into the array() method
# use tuple


arr2 = np.array((6,7,8,9,0))
print(arr2)

[6 7 8 9 0]


# dimensions in arrays

In [8]:
# 0-D arrays, or Scalars, are the elements in an array.


arr3 = np.array(22)
print(arr3)

22


In [9]:
# any array that has 0-D arrays as its elements is called 1-D array


arr4 = np.array([22,11,75,2,7])
print(arr4)

[22 11 75  2  7]


In [11]:
# any array that 1-D arrays as its elements is called 2-D array


arr5 = np.array([[1,3,5,7,9],[2,4,6,8,0]])
print(arr5)

[[1 3 5 7 9]
 [2 4 6 8 0]]


In [12]:
# an array that as 2-D arrays as its elements is called 3-D array


arr6 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [14]:
# look over number of dimensions


print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

0
1
2
3


In [16]:
# using ndmin argument in array() method the number of dimensions can be defined
# array with 5 dimensions


arr7 = np.array([5,4,3,2,1,0], ndmin=5)
print(arr7)
print(arr7.ndim)

[[[[[5 4 3 2 1 0]]]]]
5
