In [14]:
%time lict = list(range(3000000))

Wall time: 315 ms


In [10]:
import numpy as np

In [11]:
%time a = np.arange(3000000)

Wall time: 45 ms


In [12]:
a.dtype

dtype('int32')

In [15]:
type(a)

numpy.ndarray

In [16]:
a.ndim

1

In [17]:
array1 = np.array([1,2,3,4])

In [18]:
array1

array([1, 2, 3, 4])

In [19]:
array1.ndim

1

In [23]:
array2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [24]:
array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [22]:
array2.ndim

2

In [25]:
array2.shape

(3, 4)

In [27]:
l1 = [1,2,3,4]
arr = np.array(l1)
print(arr)

[1 2 3 4]


In [28]:
t1 = (1,2,3,4)
arr2 = np.array(t1)
print(arr2)

[1 2 3 4]


In [29]:
type(arr2)

numpy.ndarray

In [30]:
import numpy as np

In [31]:
a1 = np.array([1,23,5,45])

In [32]:
print(a1)

[ 1 23  5 45]


In [33]:
a2 = np.array(a1)

In [34]:
a2

array([ 1, 23,  5, 45])

In [35]:
a1 is a2

False

In [36]:
a3 = np.asarray(a1)

In [37]:
a3 is a1

True

In [38]:
a1[0] = 2

In [39]:
print(a1)

[ 2 23  5 45]


In [40]:
a3

array([ 2, 23,  5, 45])

In [41]:
lict = [1,2,3,4,5]

In [42]:
asarray = np.asarray(lict)

In [43]:
asarray

array([1, 2, 3, 4, 5])

In [44]:
asarray is lict

False

In [45]:
arange1 = np.arange(23)

In [46]:
arange1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [49]:
a1 = np.ones((2,4))

In [50]:
print(a1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [51]:
a2 = np.ones((3,1))

In [52]:
a2

array([[1.],
       [1.],
       [1.]])

In [53]:
arr1 = np.array((4,5))

In [54]:
arr1

array([4, 5])

In [55]:
arr1 = np.arange(24).reshape(4,6)

In [56]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [57]:
arr2 = np.ones_like(arr1)

In [58]:
print(arr2)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [59]:
arr3 = np.zeros_like(arr2)

In [60]:
arr3

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [61]:
arr4 = np.empty((3,4))

In [62]:
arr4

array([[1.00035371e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.06102110e-046, 1.76069625e-076,
        2.25251979e+184],
       [1.53235468e-047, 1.51038715e+160, 2.23303916e-052,
        3.57745930e-061]])

In [63]:
arr2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [64]:
arr5 = np.empty_like(arr2)

In [65]:
arr5

array([[1808858488,        471,         64,          0,          0,
                 0],
       [         0,          0,          0,          0, 1717711412,
         912482864],
       [ 912418357,  808739633, 1714500196, 1714762852,  858940729,
         909534520],
       [ 862205240, 1630613602, 1714829367,  892691301, 1714565168,
         862086497]])

In [67]:
arr6 = np.full((4,5), fill_value = 3)

In [68]:
arr6

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [70]:
arr7 = np.full_like(arr2, fill_value="22")

In [71]:
arr7

array([[22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22]])

In [72]:
arr8 = np.identity(3)

In [73]:
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
arr9 = np.identity(5)

In [76]:
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
arr10 = np.eye(3)

In [78]:
arr10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
a1 = np.array([1,3,2,5], dtype=np.float64)

In [80]:
a1

array([1., 3., 2., 5.])

In [81]:
a1.dtype

dtype('float64')

In [82]:
a2 = np.array([2,3,5,5], dtype=np.int32)

In [83]:
a2

array([2, 3, 5, 5])

In [84]:
a2.dtype

dtype('int32')