In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2 = arr.copy()

In [5]:
arr2

array([1, 2, 3, 4, 5])

In [6]:
arr2[0] = 2

In [7]:
arr2

array([2, 2, 3, 4, 5])

In [8]:
arr

array([1, 2, 3, 4, 5])

# View

In [9]:
arr = np.array([1,2,3,4,5])

In [10]:
arr2 = arr.view()

In [11]:
arr2[0] = 2

In [12]:
arr2

array([2, 2, 3, 4, 5])

In [13]:
arr

array([2, 2, 3, 4, 5])

In [14]:
arr[2] =2

In [15]:
arr

array([2, 2, 2, 4, 5])

In [16]:
arr2

array([2, 2, 2, 4, 5])

In [18]:
print(arr2.base)

[2 2 2 4 5]


In [19]:
print(arr.base)

None
