In [1]:
import numpy as np

In [2]:

lict = [2,3,4,5,6]



In [3]:
print(lict[0])

2


In [4]:
print(lict[0:2])

[2, 3]


In [5]:
lict[1:2]

[3]

In [6]:
lict[:4]

[2, 3, 4, 5]

In [8]:
lict[0:]

[2, 3, 4, 5, 6]

In [9]:
lict = ['tariq',2.3,4,'c']

In [10]:
lict

['tariq', 2.3, 4, 'c']

In [11]:
lict[0]

'tariq'

In [12]:
import numpy as np

In [13]:
a1 = np.array([1,2,3,5,4,7])

In [14]:
a1

array([1, 2, 3, 5, 4, 7])

In [15]:
a1.dtype

dtype('int32')

In [16]:
a2 = ([1,2,4,6,7])

In [18]:
type(a2)

list

In [19]:
type(a1)

numpy.ndarray

In [20]:
a2 = np.array([[1,2,3,4],[4,3,2,1],[4,3,2,1]])
print(a2)



[[1 2 3 4]
 [4 3 2 1]
 [4 3 2 1]]


In [21]:
type(a2)

numpy.ndarray

In [22]:
a2.ndim

2

In [23]:
a2.dtype

dtype('int32')

In [24]:
a3 = np.array(['tariq','shahbaz','rehan'])

In [25]:
a3

array(['tariq', 'shahbaz', 'rehan'], dtype='<U7')

In [27]:
a3.dtype

dtype('<U7')

In [28]:
a4 = np.array(['abcdefghi'])

In [29]:
a4.dtype

dtype('<U9')

In [30]:
a5 = np.array(['aa','bbb','cccc'])

In [31]:
a5.dtype

dtype('<U4')

In [32]:
a2

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [4, 3, 2, 1]])

In [34]:
a2.shape

(3, 4)

In [46]:
a6 = np.array([[[1,2,4,6],[1,2,4,3],[4,2,2,1]]])

In [47]:
a6

array([[[1, 2, 4, 6],
        [1, 2, 4, 3],
        [4, 2, 2, 1]]])

In [48]:
a6.ndim

3

In [49]:
a6.shape

(1, 3, 4)

In [50]:
lict = [1,2,4,5]
a1 = np.array(lict)

In [51]:
a1

array([1, 2, 4, 5])

In [52]:
tup = (1,2,4,5)
a2 = np.array(tup)
a2

array([1, 2, 4, 5])

In [58]:
dic ={1,2,3,4}
print(type(dic))
a3 = np.array(dic)
a3

<class 'set'>


array({1, 2, 3, 4}, dtype=object)

In [55]:
a3.dtype

dtype('O')

In [59]:
a4 = np.array(42)

In [60]:
a5 = np.array(53,35)

TypeError: data type not understood

In [65]:
arr1 = np.array([1,2,3,5], ndmin=9)

In [66]:
arr1

array([[[[[[[[[1, 2, 3, 5]]]]]]]]])

In [67]:
arr1.ndim

9

In [69]:
arr1 = np.array([1,2,4,5], dtype='int32')

In [70]:
arr1.dtype

dtype('int32')

In [80]:
arr1 = np.array([1,2,3,4], dtype ="int")

In [78]:
arr1.dtype

dtype('int16')

In [74]:
arr1 = np.array([1,2,3,4], dtype='float')

In [76]:
arr1.dtype

dtype('float64')

In [86]:
arr1 = np.array([1,2,3,4],dtype='float')
arr1.dtype

dtype('float64')

In [90]:
arr1 = arr1.astype('int')

In [91]:
arr1.dtype

dtype('int32')

In [93]:
arr1 = np.array(arr1,dtype = 'int')

In [94]:
arr1.dtype

dtype('int32')